// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.DataWarehouse
{
    public partial class DimAirports
    {
        public DimAirports()
        {
            FactFlightsDestinationAirport = new HashSet<FactFlights>();
            FactFlightsOriginAirport = new HashSet<FactFlights>();
        }

        public int AirportId { get; set; }
        public string Name { get; set; }
        public int? CityId { get; set; }
        public string Iata { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }

        public virtual DimCity City { get; set; }
        public virtual ICollection<FactFlights> FactFlightsDestinationAirport { get; set; }
        public virtual ICollection<FactFlights> FactFlightsOriginAirport { get; set; }
    }
}