// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.DataWarehouse
{
    public partial class DimCity
    {
        public DimCity()
        {
            DimAirports = new HashSet<DimAirports>();
        }

        public int CityId { get; set; }
        public string Name { get; set; }
        public int? StateId { get; set; }

        public virtual DimState State { get; set; }
        public virtual ICollection<DimAirports> DimAirports { get; set; }
    }
}