// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.DataWarehouse
{
    public partial class DimDate
    {
        public DimDate()
        {
            FactFlights = new HashSet<FactFlights>();
        }

        public int DateId { get; set; }
        public int? Year { get; set; }
        public int? Month { get; set; }
        public int? Day { get; set; }
        public int? DayOfWeek { get; set; }

        public virtual ICollection<FactFlights> FactFlights { get; set; }
    }
}