// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.DataWarehouse
{
    public partial class DimState
    {
        public DimState()
        {
            DimCity = new HashSet<DimCity>();
        }

        public int StateId { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }

        public virtual ICollection<DimCity> DimCity { get; set; }
    }
}