// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.DataWarehouse
{
    public partial class FactDelays
    {
        public int FactDelaysId { get; set; }
        public int? FactFlightsId { get; set; }
        public TimeOnly? ScheduledDeparture { get; set; }
        public TimeOnly? DepartureTime { get; set; }
        public int? DepartureDelay { get; set; }
        public TimeOnly? ScheduledArival { get; set; }
        public TimeOnly? ArivalTime { get; set; }
        public int? ArivalDelay { get; set; }

        public virtual FactFlights FactFlights { get; set; }
    }
}