// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.DataWarehouse
{
    public partial class FactFlights
    {
        public FactFlights()
        {
            FactDelays = new HashSet<FactDelays>();
        }

        public int FactFlightsId { get; set; }
        public int? DateId { get; set; }
        public int? FlightNumberId { get; set; }
        public int? AirlineId { get; set; }
        public int? OriginAirportId { get; set; }
        public int? DestinationAirportId { get; set; }
        public int? AirTime { get; set; }
        public int? Distance { get; set; }
        public bool? Canceled { get; set; }

        public virtual DimAirlines Airline { get; set; }
        public virtual DimDate Date { get; set; }
        public virtual DimAirports DestinationAirport { get; set; }
        public virtual DimFlightNumber FlightNumberNavigation { get; set; }
        public virtual DimAirports OriginAirport { get; set; }
        public virtual ICollection<FactDelays> FactDelays { get; set; }
    }
}