// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ETL.Models
{
    public partial class Airlines
    {
        public int AirlineId { get; set; }
        public string IataCode { get; set; }
        public string Airline { get; set; }
    }
}